echo "backend:
  name: git-gateway
  branch: main # Branch to update (main by default)

media_folder: \"static/img\" # Media files will be stored in the repo under static/img
public_folder: \"/img\" # The src attribute for uploaded media will begin with /img

collections:
  - name: \"pages\"
    label: \"Pages\"
    folder: \"content/pages\"
    create: true
    slug: \"{{slug}}\"
    fields:
      - { label: \"Title\", name: \"title\", widget: \"string\" }
      - { label: \"Body\", name: \"body\", widget: \"markdown\" }
  - name: \"blog\"
    label: \"Blog\"
    folder: \"content/blog\"
    create: true
    slug: \"{{slug}}\"
    fields:
      - { label: \"Title\", name: \"title\", widget: \"string\" }
      - { label: \"Body\", name: \"body\", widget: \"markdown\" }" > static/admin/config.yml